version: 2

models:
  - name: mwra_referral_followup
    config:
        tags: "mwra"
    columns:
      - name: referral_followup_id
        tests:
          - unique
          - not_null  

  - name: mwra_case
    config:
        tags: "mwra"
    columns:
      - name: case_id
        tests:
          - unique
          - not_null  

  - name: mwra_visit
    config:
        tags: "mwra"
    columns:
      - name: visit_id
        tests:
          - unique
          - not_null  
